version: '3'

services:
  sleek-airflow:
    image: apache-sleek:latest
    
    volumes:
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"

    command: airflow standalone

